'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('app/src/main/assets/app.js','utf8');
const start=source.indexOf('function normalizeQrName(');
const end=source.indexOf('function matchQrClient(',start);
assert.ok(start>=0&&end>start,'QR parser exists');
const scope={Date,Number,String};
vm.createContext(scope);
vm.runInContext(source.slice(start,end),scope);
const example=String.fromCharCode(2)+'CB0010@0001@(주)이진특@테스트차량@@25.71@한일영월@20260814@0925@삼양레미콘( @경기도 남 @테스트'+String.fromCharCode(3);
const qr=scope.parseTransportQR(example);
assert.equal(qr.valid,true);
assert.equal(qr.type,'cement-slip');
assert.equal(qr.weight,25.71);
assert.equal(qr.date,'2026. 8. 14.');
assert.equal(qr.customer,'삼양레미콘(주)');
assert.equal(qr.loading,'한일시멘트(영월)');
assert.equal(qr.carrier,'(주)이진특수');
assert.equal(qr.unloading,'경기도 남');
assert.equal(scope.parseTransportQR('https://example.invalid').valid,false);
const simple=scope.parseTransportQR('거래처:테스트;실질량:12.5');
assert.equal(simple.weight,12.5);
console.log('PASS cement QR parsing, net tonnes, date, partial destination, legacy format');
